In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('medical_premium.csv')

In [3]:
df.head()

Age  Diabetes  BloodPressureProblems  AnyTransplants  AnyChronicDiseases  \
0   45         0                      0               0                   0   
1   60         1                      0               0                   0   
2   36         1                      1               0                   0   
3   52         1                      1               0                   1   
4   38         0                      0               0                   1   

   Height  Weight  KnownAllergies  HistoryOfCancerInFamily  \
0     155      57               0                        0   
1     180      73               0                        0   
2     158      59               0                        0   
3     183      93               0                        0   
4     166      88               0                        0   

   NumberOfMajorSurgeries  PremiumPrice  
0                       0         25000  
1                       0         29000  
2                       1         23000  
3                       2         28000  
4                       1         23000

In [4]:
df.shape

(986, 11)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 986 entries, 0 to 985
Data columns (total 11 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Age                      986 non-null    int64
 1   Diabetes                 986 non-null    int64
 2   BloodPressureProblems    986 non-null    int64
 3   AnyTransplants           986 non-null    int64
 4   AnyChronicDiseases       986 non-null    int64
 5   Height                   986 non-null    int64
 6   Weight                   986 non-null    int64
 7   KnownAllergies           986 non-null    int64
 8   HistoryOfCancerInFamily  986 non-null    int64
 9   NumberOfMajorSurgeries   986 non-null    int64
 10  PremiumPrice             986 non-null    int64
dtypes: int64(11)
memory usage: 84.9 KB


In [6]:
df.isnull().sum()

Age                        0
Diabetes                   0
BloodPressureProblems      0
AnyTransplants             0
AnyChronicDiseases         0
Height                     0
Weight                     0
KnownAllergies             0
HistoryOfCancerInFamily    0
NumberOfMajorSurgeries     0
PremiumPrice               0
dtype: int64

In [7]:
x = df.iloc[:,:-1].values

In [8]:
x

array([[45,  0,  0, ...,  0,  0,  0],
       [60,  1,  0, ...,  0,  0,  0],
       [36,  1,  1, ...,  0,  0,  1],
       ...,
       [56,  0,  1, ...,  0,  0,  1],
       [47,  1,  1, ...,  1,  0,  1],
       [21,  0,  0, ...,  1,  0,  1]])

In [9]:
y = df.iloc[:,-1].values

In [10]:
y

array([25000, 29000, 23000, 28000, 23000, 23000, 21000, 15000, 23000,
       23000, 28000, 25000, 15000, 35000, 15000, 23000, 30000, 23000,
       25000, 15000, 28000, 15000, 32000, 23000, 35000, 21000, 15000,
       28000, 23000, 21000, 15000, 19000, 15000, 15000, 28000, 28000,
       23000, 25000, 30000, 15000, 15000, 28000, 15000, 29000, 15000,
       23000, 32000, 35000, 25000, 15000, 23000, 28000, 28000, 32000,
       25000, 23000, 29000, 28000, 24000, 23000, 23000, 25000, 15000,
       23000, 28000, 15000, 28000, 15000, 23000, 21000, 15000, 30000,
       25000, 38000, 28000, 28000, 15000, 23000, 28000, 38000, 23000,
       25000, 15000, 23000, 25000, 25000, 38000, 15000, 31000, 21000,
       25000, 28000, 31000, 28000, 28000, 15000, 23000, 23000, 25000,
       23000, 15000, 38000, 31000, 15000, 15000, 23000, 25000, 23000,
       19000, 28000, 29000, 23000, 15000, 23000, 23000, 19000, 28000,
       25000, 25000, 21000, 28000, 29000, 23000, 15000, 23000, 38000,
       30000, 31000,

In [11]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

In [12]:
from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor(n_estimators = 10, random_state = 0)
regressor.fit(x_train, y_train)

RandomForestRegressor(n_estimators=10, random_state=0)

In [13]:
y_pred = regressor.predict(x_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[23000. 23000.]
 [23000. 23000.]
 [28000. 28000.]
 [24600. 23000.]
 [33700. 38000.]
 [23000. 23000.]
 [15100. 15000.]
 [29000. 29000.]
 [25000. 25000.]
 [33200. 35000.]
 [23000. 23000.]
 [23000. 23000.]
 [15000. 15000.]
 [25000. 25000.]
 [27600. 30000.]
 [15000. 15000.]
 [23700. 23000.]
 [29000. 29000.]
 [15900. 15000.]
 [28000. 40000.]
 [20800. 15000.]
 [28000. 28000.]
 [23000. 23000.]
 [18400. 15000.]
 [23400. 19000.]
 [38000. 38000.]
 [23000. 23000.]
 [25000. 25000.]
 [29000. 29000.]
 [32800. 35000.]
 [33200. 35000.]
 [15000. 15000.]
 [20400. 15000.]
 [18300. 15000.]
 [25000. 25000.]
 [23000. 23000.]
 [23000. 23000.]
 [25000. 25000.]
 [25000. 25000.]
 [22800. 19000.]
 [28000. 28000.]
 [22800. 19000.]
 [23000. 23000.]
 [24700. 19000.]
 [24500. 23000.]
 [15000. 15000.]
 [28000. 28000.]
 [17300. 39000.]
 [29000. 29000.]
 [28000. 28000.]
 [15000. 15000.]
 [22200. 21000.]
 [15000. 15000.]
 [28000. 28000.]
 [30000. 30000.]
 [28000. 28000.]
 [23400. 25000.]
 [28000. 28000.]
 [35000. 35000

In [14]:
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

0.6609213383287389

In [16]:
import pickle
pickle.dump(regressor,open('model.pkl','wb'))